### ISSUE TITLE
Not able read from db file from ByteArrayInputstream

### ISSUE THREAD

**Issue by manojshankar** [maxmind/GeoIP2-java#80] opened 2016-12-21 05:50 UTC
When database file is read into ByteArrayInputstream and used in Reader. Getting below exception.

DatabaseReader reader = new DatabaseReader.Builder(stream).withCache(new CHMCache()).build();

error
Could not find a MaxMind DB metadata marker in this file (<InputStream>). Is this a valid MaxMind DB file?

**Comment by oschwald** [comment] 2016-12-21 14:31
Opening from an input stream is [tested](https://github.com/maxmind/GeoIP2-java/blob/master/src/test/java/com/maxmind/geoip2/DatabaseReaderTest.java#L29). Do you have a standalone test that shows the issue you are experiencing? If you are loading it from a Jar file, you likely need to disable resource filtering in Maven. If you are loading it from a file directly, please be sure that you have decompressed it first.

**Comment by manojshankar** [comment] 2016-12-21 19:45
`public class GeoIPTest3 {
	private InputStream geoipStream;
	
	@Before
    public void setup() throws URISyntaxException, IOException {
		 File file = new File("C:/tmp/GeoIP2-Anonymous-IP_20161218/GeoIP2-Anonymous-IP.mmdb");
	     byte[] bytefile = FileUtils.readFileToByteArray(file);
	     this.geoipStream = new ByteArrayInputStream(bytefile);
    }
	
	@Test
    public void testStreamFile() throws Exception {
        DatabaseReader reader = new DatabaseReader.Builder(this.geoipStream)
                .build();
        InetAddress ipAddress = InetAddress.getByName("119.23.170.36");
        AnonymousIpResponse response = reader.anonymousIp(ipAddress);
        System.out.println(response);
        /*assertTrue(response.isAnonymous());
        assertTrue(response.isAnonymousVpn());
        assertFalse(response.isHostingProvider());
        assertFalse(response.isPublicProxy());
        assertFalse(response.isTorExitNode());
        assertEquals(ipAddress.getHostAddress(), response.getIpAddress());*/
        reader.close();
    }
}`

It is working in older version in 2.5.3

**Comment by oschwald** [comment] 2016-12-21 21:24
@manojshankar, I tried reproducing it at https://github.com/maxmind/GeoIP2-java/compare/greg/test-byte-array?expand=1#diff-2d8319cf2ce70c8ea9d0bd1c6affa89cR110, but I was not able to. Are you sure your mmdb file is valid? Do you have the md5sum for the file?

**Comment by oschwald** [comment] 2017-01-03 14:40
I am closing this as I was not able to reproduce it with the code above. I am happy to re-open if you provide a self-contained test case.

**Closed by oschwald** 2017-01-03 14:40 UTC
