### ISSUE TITLE
ERROR: java.lang.ClassCastException: Cannot cast java.lang.String to com.maxmind.geoip2.model.AsnResponse.

### ISSUE THREAD

**Issue by ScXin** [maxmind/GeoIP2-java#270] opened 2021-09-19 03:26 UTC
Hi, 

 I have used the com.maxmind.geoip2.geoip2-2.1.50 maven repo to match the asn info in Java. The used mmdb file is produced by mmdb writer(https://github.com/maxmind/mmdbwriter.git). However, this following error comes after the program run a range of time:

 ```
ERROR: java.lang.ClassCastException: Cannot cast java.lang.String to com.maxmind.geoip2.model.AsnResponse.
```

I don't know why this error happen. Who can help me?

**Comment by oschwald** [comment] 2021-09-19 17:43
It sounds like you are inserting strings directly into the database. The MaxMind ASN database has a structure similar to the one in this example:

https://github.com/maxmind/mmdbwriter/blob/efe6d8ec58163fddff546376a8c2e8b9d0c38114/examples/asn-writer/main.go#L62-L70

If you want to decode a database where the data is just a string, you will need to used [`maxmind-db`](https://github.com/maxmind/MaxMind-DB-Reader-java/) directly. I think something like this would work:

```java
import com.maxmind.db.Reader;

import java.io.File;
import java.io.IOException;
import java.net.InetAddress;

public class Lookup {
    public static void main(String[] args) throws IOException {
        File database = new File("/path/to/database/custom-database.mmdb");
        try (Reader reader = new Reader(database)) {
            InetAddress address = InetAddress.getByName("24.24.24.24");

            String result = reader.get(address, String.class);

            System.out.println(result);
        }
    }
}
```

**Comment by oschwald** [comment] 2021-09-22 22:25
Closing as I believe the above should solve this and the issue isn't directly related to this package.

**Closed by oschwald** 2021-09-22 22:25 UTC
