### ISSUE TITLE
Performance issue GeoIP2 vs GeoIP Legacy

### ISSUE THREAD

**Issue by evengard88** [maxmind/GeoIP2-java#68] opened 2016-04-19 10:42 UTC
I'm testing GeoIP2 vs GeoIP and getting a very strange result, it seems  the new api is way slower.
maxMind1 - Legacy API
maxMind2 - new API, FileMode.MEMORY_MAPPED
maxMind2v2 - new API, FileMode.MEMORY
Caches are on;

Here are my benchmark results:

```
Benchmark                      Mode     Cnt       Score      Error  Units
MindMaxBenchmark.maxMind1     thrpt      50  176225.276 ± 1603.768  ops/s
MindMaxBenchmark.maxMind2     thrpt      50     825.766 ±   12.428  ops/s
MindMaxBenchmark.maxMind2v2   thrpt      50     767.863 ±   35.938  ops/s
MindMaxBenchmark.maxMind1      avgt      50      ≈ 10⁻⁵              s/op
MindMaxBenchmark.maxMind2      avgt      50       0.001 ±    0.001   s/op
MindMaxBenchmark.maxMind2v2    avgt      50       0.001 ±    0.001   s/op
MindMaxBenchmark.maxMind1    sample  131466      ≈ 10⁻⁵              s/op
MindMaxBenchmark.maxMind2    sample   38187       0.001 ±    0.001   s/op
MindMaxBenchmark.maxMind2v2  sample   34064       0.001 ±    0.001   s/op
MindMaxBenchmark.maxMind1        ss      50      ≈ 10⁻⁴              s/op
MindMaxBenchmark.maxMind2        ss      50       0.028 ±    0.005   s/op
MindMaxBenchmark.maxMind2v2      ss      50       0.026 ±    0.004   s/op
```

Services are initialized at the test start like that:

```
final DatabaseReader mindMaxDB = new DatabaseReader.Builder(...)
                    .withCache(new CHMCache())
                    .fileMode(Reader.FileMode.MEMORY)
                    .build();
```

and the test code is like (some null checks are ommited): 

```
        public LocationData resolve(InetAddress inetAddress) {

                CityResponse cityResponse = mindMaxDB.city(inetAddress);
                Location location = cityResponse.getLocation();
                return new LocationData(
                        inetAddress, cityResponse.getCountry().getIsoCode(), cityResponse.getCity().getName()
                );
            }
```

The Legacy API: 
Service created like that 

```
LookupService lookupService = new LookupService(file, LookupService.GEOIP_MEMORY_CACHE);
```

and test code is

```
 com.maxmind.geoip.Location location = lookupService.getLocation(inetAddress);
                            return new LocationData(
                                    inetAddress, location.countryCode,
                                    location.city);
```

I'd like to know if I'm missing something?

**Comment by oschwald** [comment] 2016-04-19 13:57
I am not quite sure how to read or interpret your benchmark results based on what you posted. This library is slower than the legacy API for two reasons: (1) the search tree is much deeper as it includes IPv6 address, (2) we include considerably more data for each IP. That said, a lookup should be on the order of 20μs on modern hardware once the caches are warm.

**Comment by rudgirello** [comment] 2016-05-05 22:14
We are seeing similar results in our system (RTB domain). GeoIP Legacy appears to be 500 times faster. Pretty staggering. Our average query time for the Legacy City DB is ~8 microseconds, for GeoIP2 - ~5 milliseconds. I believe this is due to the massive size of the new V2 DB and due to the various encodings causing substantial overhead. Perhaps, it's a good idea to provide a way to turn off secondary encodings.

**Comment by oschwald** [comment] 2016-05-05 22:17
If your queries are taking 5 ms, there is almost certainly something wrong. Are you opening the database for every request?

**Comment by rudgirello** [comment] 2016-05-05 22:33
No, our usage pattern was quite optimal, as far as I could see. To be fair, we did have to alleviate a couple of synchronized blocks in the V1 client code; it's a custom build that is. And, btw, by encodings I meant locales. 

Is this the only issue tracking the performance of the V2 client? Given the great spec for the MMDB format, we are considering writing our own fast client based on it. Of course, we'd rather not do it, given the wheel has already been invented...

**Comment by rudgirello** [comment] 2016-05-05 22:36
@oschwald, provided you are surprised to see such high query time figures, what are the expected figures? What hardware did you use? We are running spinning disks (commodity 10K RPM), 16GB RAM (12GB heap), 24 logical cores, Debian 7.

**Comment by oschwald** [comment] 2016-05-05 22:49
20 μs would be in the normal range with modern commodity hardware. If you think spinning disks are an issue (my test machines have SSDs), you could try memory mode. You could also try enabling the caching as mentioned in the documentation.

**Comment by evengard88** [comment] 2016-05-06 08:54
I have used memory mode in my tests, the database is opened once, caches are on and the average time is still 1 millisecond per request. 
It seems to me that something is configured wrongly and my test is a copy-paste from the documentation;

Could you post the code that would give 20 μs per request?

**Comment by oschwald** [comment] 2016-05-06 13:46
Sure, [here is a benchmark](https://gist.github.com/oschwald/39040ab3fda9845d35b165811a62582d). On my machine, I get about 105,000 lookups per second without caching and 225,000 lookups per second with caching. This is about 9.5 μs and 4 μs per lookup.

**Comment by rudgirello** [comment] 2016-05-06 15:49
@oschwald, these are the values that we observed too for a **single thread**. The slow downs manifest themselves as we add and increase concurrency. At around 20-30 concurrent queries we are at the 1-5ms figures. At this scale any synchronized block potentially kills your performance. In this regard, Locale instances must be treated with utmost care as their retrieval involves "synchronized" like there's no tomorrow.

**Comment by oschwald** [comment] 2016-05-06 15:53
Unlike the legacy API, this API does not synchronize internally. If you have a reproducible benchmark that shows an issue, I am happy to look at it.

**Comment by rudgirello** [comment] 2016-05-06 16:31
@oschwald, we'll try to set up a benchmark reproducing this behaviour. It might be tricky, as the specificity of user traffic may have a profound effect (e.g., IP address clashes). Will get back to you next week. Thanks for looking into this!

**Comment by evengard88** [comment] 2016-05-10 08:44
I've just tried single thread version with my benchmark, it works much faster, so the behavior is reproduced.

My benchmark is written with jmh, i could share it if needed/

**Comment by oschwald** [comment] 2016-05-10 13:51
Please do share your benchmark. If there is some sort of locking issue when using a reader from multiple threads, I'd like to fix it.

**Comment by evengard88** [comment] 2016-05-10 16:39
here is my benchmark
https://github.com/evengard88/bench

test.ParamsHolder - holds parameters (ip addresses), could be modified to read from external sources.
test.MaxMind2Holder - Service holder, wraps com.maxmind.geoip2.DatabaseReader. Addresses to DB file should be modified.
test.jmh.MindMaxBenchmark - the benchmark. Annotations could be modified to watch different modes (multi-thread vs single thread and etc)

the whole thing started with
mvn clean package && java -Xmx500m -Xms500m -Djmh.ignoreLock=true -jar target/benchmarks.jar

**Comment by oschwald** [comment] 2016-05-11 22:28
I tried running the benchmark from that repo, but I received null pointer exceptions from what appears to be the IP address generation code:

```
java.lang.NullPointerException
	at test.jmh.MindMaxBenchmark.maxMind1(MindMaxBenchmark.java:57)
	at test.jmh.generated.MindMaxBenchmark_maxMind1_jmhTest.maxMind1_thrpt_jmhStub(MindMaxBenchmark_maxMind1_jmhTest.java:105)
	at test.jmh.generated.MindMaxBenchmark_maxMind1_jmhTest.maxMind1_Throughput(MindMaxBenchmark_maxMind1_jmhTest.java:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:430)
	at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:412)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)



# Run progress: 3.70% complete, ETA 00:02:39
# Fork: 2 of 3
# Warmup Iteration   1: <failure>

java.lang.NullPointerException
	at test.jmh.MindMaxBenchmark.maxMind1(MindMaxBenchmark.java:57)
	at test.jmh.generated.MindMaxBenchmark_maxMind1_jmhTest.maxMind1_thrpt_jmhStub(MindMaxBenchmark_maxMind1_jmhTest.java:105)
	at test.jmh.generated.MindMaxBenchmark_maxMind1_jmhTest.maxMind1_Throughput(MindMaxBenchmark_maxMind1_jmhTest.java:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:430)
	at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:412)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)



# Run progress: 7.40% complete, ETA 00:02:33
# Fork: 3 of 3
# Warmup Iteration   1: <failure>

java.lang.NullPointerException
	at test.jmh.MindMaxBenchmark.maxMind1(MindMaxBenchmark.java:57)
	at test.jmh.generated.MindMaxBenchmark_maxMind1_jmhTest.maxMind1_thrpt_jmhStub(MindMaxBenchmark_maxMind1_jmhTest.java:105)
	at test.jmh.generated.MindMaxBenchmark_maxMind1_jmhTest.maxMind1_Throughput(MindMaxBenchmark_maxMind1_jmhTest.java:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:430)
	at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:412)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by oschwald** [comment] 2016-05-11 22:34
I tried running the benchmark from that repo, but I received null pointer exceptions from what appears to be the IP address generation code:

```
java.lang.NullPointerException
	at test.jmh.MindMaxBenchmark.maxMind1(MindMaxBenchmark.java:57)
	at test.jmh.generated.MindMaxBenchmark_maxMind1_jmhTest.maxMind1_thrpt_jmhStub(MindMaxBenchmark_maxMind1_jmhTest.java:105)
	at test.jmh.generated.MindMaxBenchmark_maxMind1_jmhTest.maxMind1_Throughput(MindMaxBenchmark_maxMind1_jmhTest.java:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:430)
	at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:412)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)



# Run progress: 3.70% complete, ETA 00:02:39
# Fork: 2 of 3
# Warmup Iteration   1: <failure>

java.lang.NullPointerException
	at test.jmh.MindMaxBenchmark.maxMind1(MindMaxBenchmark.java:57)
	at test.jmh.generated.MindMaxBenchmark_maxMind1_jmhTest.maxMind1_thrpt_jmhStub(MindMaxBenchmark_maxMind1_jmhTest.java:105)
	at test.jmh.generated.MindMaxBenchmark_maxMind1_jmhTest.maxMind1_Throughput(MindMaxBenchmark_maxMind1_jmhTest.java:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:430)
	at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:412)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)



# Run progress: 7.40% complete, ETA 00:02:33
# Fork: 3 of 3
# Warmup Iteration   1: <failure>

java.lang.NullPointerException
	at test.jmh.MindMaxBenchmark.maxMind1(MindMaxBenchmark.java:57)
	at test.jmh.generated.MindMaxBenchmark_maxMind1_jmhTest.maxMind1_thrpt_jmhStub(MindMaxBenchmark_maxMind1_jmhTest.java:105)
	at test.jmh.generated.MindMaxBenchmark_maxMind1_jmhTest.maxMind1_Throughput(MindMaxBenchmark_maxMind1_jmhTest.java:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:430)
	at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:412)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by evengard88** [comment] 2016-05-12 08:58
My bad, fixed, tested.

**Comment by rudgirello** [comment] 2016-05-19 21:03
@oschwald, our tests eventually concluded that the problem is indeed with deserializing localized names. Do you think it's possible for MaxMind to provide clients with a database file containing only the English names?

**Comment by oschwald** [comment] 2016-05-19 21:49
We have no plans to create English-only databases, but you could email [support@maxmind.com](support@maxmind.com) with a feature request.

Some of the APIs in other languages only deserialize data that is present in the model class, but this is not currently possible with the Java API and would require significant work to implement.

As far as an immediate solution, you could try increasing the capacity of the cache and making sure your reader object lives as long as possible.

**Comment by Ankith2612** [comment] 2016-10-12 11:14
I have also been facing the same performance issue with the GeoIP2, we have used CHMCache but still the issue persist. 
In the last statement you have recommended to increase the cache capacity, could you please tell me how can i increase the capacity of the cache so that i can improve in performance.

**Comment by oschwald** [comment] 2016-10-12 14:05
You can set the capacity when creating the `CHMCache` by passing the constructor a single parameter. The default is 4096. This is how many objects it stores in the cache.

**Comment by Ankith2612** [comment] 2016-10-13 06:35
@oschwald I have tried increasing the cache but with that as well there is no optimum performance improvement. Currently we are utilizing the MaxMind database file from a HiveUDF written in java. With the default cache it was taking around 8 min to execute a query, after increasing the cache capacity to about 256 MB it is executing in 7 min. 
Could you please let me if there is anything else that i need to do in order to make the queries run efficiently.. ?

**Comment by oschwald** [comment] 2016-10-13 13:51
@Ankith2612, it sounds like something is very wrong. On my machine, I get about 100,000 lookups per second with no cache and  220,000 per second with the default cache size. Do you have code that can reproduce your issue that you can share? If is only happens in a larger application, you may need to do some profiling to determine the cause. I am not familiar enough with Hive to provide any specific advice about integrating with it.

**Comment by leus** [comment] 2017-08-17 13:20
No matter what cache / size / whatever, the new format is way too slow for bulk processing.

Is there a way to create files in the old format using the new database data? I understand some data would have to be converted (A1, A2 "countries", etc.) and of course some data will be lost, but we won't miss it since we are not using it anyways.

**Comment by horgh** [comment] 2017-08-17 17:19
Hi @leus. We don't have a way to convert from the GeoIP2 format to the legacy format.

Would you be able to share any info about the performance you're seeing vs. what you expect?

**Comment by leus** [comment] 2017-08-17 17:33
@horgh we perform many lookups over a very large dataset. Results went from 1 hour to around 10.

The old format suits us well, since it's fast and small. But apparently the old format database is not as accurate (or so I've been told) so we had to switch.

Now I'm looking at the code to find a good way to traverse / iterate the database (been at it a couple of hours but not making much progress.) This way I could just transform in-memory to a quick and dirty structure and perform binary searchs on it.

Any hints are welcome.

**Comment by horgh** [comment] 2017-08-17 19:42
Interesting. Do you know how many lookups per second you're seeing with each format?

For the specific task you mention involving loading the entire database into your own data structure, one possibility might be to read in the CSV format instead. I believe the API here is not designed for that purpose.

Another option may be to use a library that provides iteration of the database, though I don't think there is one with such functionality for Java. [The lower level Perl library can though](https://metacpan.org/pod/MaxMind::DB::Reader).

**Comment by leus** [comment] 2017-08-17 19:53
Thanks. I got some paraphrased numbers so I can't really say, but as I said, it was enough of an issue so action is needed.

We are trying not to disturb the current process; database files are already available to the application. But if I have to take an extra day just to look into ways to read this information we may use those CSV files instead.

I did look at the Perl library, but its approach is too different from the Java one for me to get a good idea on how to implement my own version. And we are working inside a Hadoop / Java world, so I can't really use the Perl library directly.

I was thinking on going directly to the Output Data section in the database, but I don't see an easy way to get each record size...

**Comment by horgh** [comment] 2017-08-18 01:06
I see. Thank you for the information.

What you suggest seems possible, though I'm not sure how difficult it will be. I don't have a similar implementation to refer you to.

The Perl reader's iteration appears to descend the binary search tree rather than going directly to the output data. It might be worth trying to port that. An unofficial Go reader [also does this](https://github.com/oschwald/maxminddb-golang/blob/master/traverse.go).

Regarding the sizes in the output data:

I expect you've seen this, but the spec explains that section: http://maxmind.github.io/MaxMind-DB/

It looks like [this part of the Java MMDB reader](https://github.com/maxmind/MaxMind-DB-Reader-java/blob/master/src/main/java/com/maxmind/db/Decoder.java#L131) may be useful to look at.

**Comment by leus** [comment] 2017-08-18 12:16
> It looks like this part of the Java MMDB reader may be useful to look at.

Yuck. Yes, I've seen that, couldn't decouple it to make it work. I'll take a last look at the Perl reader.

**Comment by hc-codersatlas** [comment] 2018-05-30 09:55
Has someone actually benchmarked / profiled this? Are we sure the bottleneck is the way the file is read and/or the new format? I looked through the source code of the MaxMind-DB-Reader-java as that's where I assume the bulk of the problem is. My thoughts are there are too many objects created causing lots of garbage collection.

I for 1 don't understand Jackson's role in this. It's a binary format and meant to be high performance. This doesn't seem to be a good fit for low level Json serialization/deserialization.

**Comment by hc-codersatlas** [comment] 2018-06-08 05:58
Spent some time looking into this. Jackson `ObjectMapper` are created many times throughout the calls in both `AbstractResponse` and `AbstractRecord`. Jackson notes that these calls are expensive and these can be reused. There's a single `ObjectMapper` in database reader that might be causing the multi-threaded slowdown.

**Comment by oschwald** [comment] 2018-06-08 14:04
@hc-codersatlas, those objects are only used when serializing the object to JSON. They are not used when doing database lookups or web service calls. If you are serializing many objects to JSON, I would suggest creating your own object mapper and not using the `toJson()` methods.

We are happy to review PRs for performance improvements that are backed by profiling data or noticeable benchmark improvements.

**Comment by catap** [comment] 2018-06-08 14:11
@hc-codersatlas, @oschwald I'm working on this issue on my free time. I hope soon come back here with some results ;)

**Comment by catap** [comment] 2018-08-05 22:26
As I promised I pushed some changes that should decrease (dramatically) allocation rate https://github.com/maxmind/MaxMind-DB-Reader-java/pull/37

It still uses jackson as the way to convert decoded data to Java classes.

I had some ideas but it request more time.

**Comment by catap** [comment] 2018-08-06 01:10
BTW jackson costs about 50% of CPU time

<img width="1392" alt="screen shot 2018-08-06 at 05 06 48" src="https://user-images.githubusercontent.com/37775/43692191-8ae3f85c-9936-11e8-94d2-c585f1b871dc.png">

**Comment by hc-codersatlas** [comment] 2018-08-06 01:14
@catap I mentioned the Jackson issue some posts back already but according to @oschwald it's not being used.

**Comment by oschwald** [comment] 2018-08-06 01:25
Jackson's data binding is definitely being used. However, the `ObjectMapper` referred to above in `AbstractResponse` and `AbstractRecord` is only used to serialize to JSON when you explicitly call `toJson()`

**Comment by luann-trend** [comment] 2019-01-16 22:20
Does anybody know what is the status of this issue ? Do we have a fix or the fix has been merged ?

**Comment by p00temkin** [comment] 2019-02-09 11:32
Anything blocking a 2.12.1 release with this one?

**Comment by hc-codersatlas** [comment] 2019-08-23 08:38
@oschwald any chance of a release?

**Comment by davseitsev** [comment] 2019-10-07 07:43
My investigation showed a few places to improve performance.
First of all using Jackson is definitely the issue. The database itself doesn't store JSON records.
Jackson is used only convenient mapping of internally stored object to any custom DTO like CityResponse, CountryResponse etc. And this operation is quite expensive. Profiling shows that:
 1. without caching, lookup and decoding to JsonNode tree takes 57%, binding to DTO 40% (of DatabaseReader.get method)
 2. with caching, lookup and decoding to JsonNode tree takes 26%, binding to DTO 72%

Another thing to improve in my opinion is decoder cache. Currently it stores first 4000 decoded pointer values. As a result most part of the cache is taken by Double values. It would be better to store only Maps, Arrays and Strings to cache as their decoding is the most expensive.

Also it would be good to add push-down filter for locales.

I tried implementing my own reader with 1 - reflection binding but without Jackson, 2 - with filtering only relevant type in cache and 3 - with decoding only EN locale.
The tests showed significant performance improvement (3 times on my real dataset). Now the most expensive operation is decoding strings.

IP lookup itself is extremely efficient, less than 1% of time.

**Comment by oschwald** [comment] 2019-10-07 14:18
@davseitsev, I agree that the biggest win would come from replacing `jackson-databind` and deserializing to the model classes ourselves using reflect. This is what both the .NET and Go readers do. This also allows for optimizations such as not deserializing data that does not appear in the particular class being deserialized to, which can greatly speed up lookups if you only need a few fields.

The decoder cache was intentionally made to be pluggable. The one included with the decoder is extremely simplistic and was mostly created as an example of how to write a cache. A more full-featured one would likely use be an LRU implementation.

**Comment by oschwald** [comment] 2021-04-30 22:33
Since I last commented, we replaced `jackson-databind` for deserializing the model classes, which helps somewhat. I am going to go ahead and close this issue as it isn't specific enough to be actionable. There are certainly inefficiencies in the data format design, but that is out of scope for this particular reader. There are likely some changes that could improve performance to the Java reader, but several different people have spent time profiling and improving the code over the years. Any changes would likely be to `maxmind-db` rather than this higher level API.

**Closed by oschwald** 2021-04-30 22:33 UTC
